### ISSUE TITLE
Python script source code

### ISSUE THREAD

**Issue by dstubbs95** [sbenkorichi/mult_mesh_generator#1]
Would it be possible for you to add your python source code for the app to this repository? I would be interested in using it locally and it seems you have added some quality of life improvements over the version available in the FDS repository (prints out the &MESH and &MULT line, doesn't assume centered around 0).

**Comment by sbenkorichi** [comment]
The original file is written by Randy, 
I've included the file I'm using for the gui web. You can find it [here ](https://github.com/sbenkorichi/mult_mesh_generator/blob/master/mult_mesh.py)

**Comment by dstubbs95** [comment]
Awesome, thank you!
